export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST"
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS"
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL"

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL"

export const ADMIN_CATEGORY_REQUEST = "ADMIN_CATEGORY_REQUEST"
export const ADMIN_CATEGORY_SUCCESS = "ADMIN_CATEGORY_SUCCESS"
export const ADMIN_CATEGORY_FAIL = "ADMIN_CATEGORY_FAIL"

export const CREAT_CATEGORY_REQUEST = "CREAT_CATEGORY_REQUEST"
export const CREAT_CATEGORY_SUCCESS = "CREAT_CATEGORY_SUCCESS"
export const CREAT_CATEGORY_FAIL = "CREAT_CATEGORY_FAIL"

export const CATEGORY_DETAILS_REQUEST = "CATEGORY_DETAILS_REQUEST"
export const CATEGORY_DETAILS_SUCCESS = "CATEGORY_DETAILS_SUCCESS"
export const CATEGORY_DETAILS_FAIL = "CATEGORY_DETAILS_FAIL"

export const CLEAR_ERRORS ='CLEAR_ERRORS'