export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST"
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS"
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL"
export const ADMIN_PRODUCT_RESET = "ADMIN_PRODUCT_RESET"

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL"

export const REMOVE_PRODUCT_REQUEST = "REMOVE_PRODUCT_REQUEST"
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS"
export const REMOVE_PRODUCT_FAIL = "REMOVE_PRODUCT_FAIL"

export const ADMIN_CATEGORY_REQUEST = "ADMIN_CATEGORY_REQUEST"
export const ADMIN_CATEGORY_SUCCESS = "ADMIN_CATEGORY_SUCCESS"
export const ADMIN_CATEGORY_FAIL = "ADMIN_CATEGORY_FAIL"
export const ADMIN_CATEGORY_RESET = "ADMIN_CATEGORY_RESET"

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST"
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS"
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL"

export const REMOVE_CATEGORY_REQUEST = "REMOVE_CATEGORY_REQUEST"
export const REMOVE_CATEGORY_SUCCESS = "REMOVE_CATEGORY_SUCCESS"
export const REMOVE_CATEGORY_FAIL = "REMOVE_CATEGORY_FAIL"

export const ALL_USER_REQUEST = "ALL_USER_REQUEST"
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS"
export const ALL_USER_FAIL = "ALL_USER_FAIL"

export const CLEAR_ERRORS ='CLEAR_ERRORS'